# Generated by Django 5.0.4 on 2024-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEALER', models.CharField(choices=[('3504HB', 'HB IMARÉS'), ('0823HB', 'HMB - ERMANO MARQUETTI'), ('0742HB', 'HMB SANTANA - AVIAÇÃO'), ('0904HB', 'HMB CONSOLAÇÃO'), ('0157HB', 'HMB - NACOES UNIDAS MATRIZ'), ('0110FO', 'FORD IBIRAPUERA'), ('1633HB', 'HMB RECIFE'), ('2414CH', 'CHERY - IMBIRIBEIRA'), ('1604CH', 'CHERY - CAMPINA GRANDE'), ('7300CH', 'CHERY - JOÃO PESSOA'), ('212FO', 'FORD JOÃO PESSOA'), ('2877HB', 'HMB CAMPINA GRANDE'), ('5800HY', 'HYUNDAI CAOA EPITÁCIO'), ('0408HB', 'HMB - SAO BERNARDO'), ('0661HB', 'HMB SANTO ANDRÉ')], max_length=50)),
                ('NomeLoja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=50)),
                ('data_servico', models.DateField()),
                ('descricao_pedido', models.TextField()),
                ('tmos_selecionados', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TMO', models.CharField(choices=[('STLAVSIM', 'Lavagem Simples'), ('STPREPS', 'Preparação de Seminovos'), ('STLAVCRISTAL', 'Lavagem com Cera + Cristalização para Brisa'), ('STKITPLUS', 'Kit Plus - Kit3x1 - Polimento + Selante + Higienização Interna + Hidratação de Banco + Cristalização de Vidros'), ('STLAVMOT', 'Lavagem com Motor'), ('STPREPN', 'Preparação de Novos'), ('STHIGIE', 'Higienização de Bancos e Teto'), ('STCERAMIC9H', 'Vitrificação de Pintura 9H ou 10H (Polimento + Cristalização + 9H ou 10H)'), ('STREMOP', 'Remoção de Pelicula'), ('STCRIV', 'Serv. Terc. - Cristalização de vidros'), ('STHIDBA', 'Serv. Terc. - Hidratação dos bancos'), ('STKIT31', 'Serv. Terc. - KIT3x1 - Polimento + Selante + Higienização interna + hidratação de banco'), ('STKITION', 'Serv. Terc. - Polimento + Selante'), ('STVITRI', 'Vitrificação de Pintura 5h (polimento + Cristaçiza + 5h)')], max_length=50)),
                ('DescServ', models.CharField(max_length=255)),
                ('CustoUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ValorCAOA', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
