# Generated by Django 5.0.4 on 2024-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissaoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
    ]
