# Generated by Django 5.0.4 on 2024-05-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0002_emissaoordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissaoordemservico',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
